services:
  db_service:
    image: postgres:16
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=${POSTGRES_DB}  # Adicionado banco, usuário e senha
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}  # Isso permite acesso sem senha
    ports:
      - "${DB_PORT}:5432"
    networks:
    - app-net

  app_service:
    build: . # indica o dockerfile
    container_name: spring_app # nome específico do container

    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      - db_service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - app-net
      
volumes:
  postgres_data:

networks:
  app-net:
